tiendajuegos/juegos/urls.py
from django.urls import path
from .views import index, registro, login, juegos, agregar_juego, eliminar_juego, restar_juego, limpiar_carrito, carritoVer

urlpatterns = [
    path('inicio', index, name='inicio'),
    path('registro', registro, name='registro'),
    path('login', login, name='login'),
    path('juegos', juegos, name='juegos'),
    path('carrito', carritoVer, name='carrito'),

    
    path('agregar_juego/<int:juego_id>/', agregar_juego, name='agregar_juego'),
    path('eliminar/<int:juego_id>/', eliminar_juego, name="Del"),
    path('restar/<int:juego_id>/', restar_juego, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
]

tiendajuegos/tiendajuegos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', include('juegos.urls')),
    path('admin/', admin.site.urls), 
    path('', RedirectView.as_view(url='inicio')),

    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tiendajuegos/juegos/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre
class Juego(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='juegos/', null=True, blank=True)
    precio = models.IntegerField()
    stock = models.IntegerField()
    juego_id = models.AutoField(primary_key=True)

    def __str__(self):
        return self.nombre

tiendajuegos/juegos/views.py
from django.shortcuts import render, redirect

from .Carrito import Carrito
from .models import Juego, Categoria

from django.contrib.sessions.models import Session
from django.contrib.sessions.backends.db import SessionStore



def index(request):
    categorias = Categoria.objects.all()
    context = {
        'categorias': categorias,
    }
    return render(request, 'index.html', context)

def registro(request):
    return render(request, 'registro.html')

def login(request):
    return render(request, 'login.html')

def juegos(request):
    juegos = Juego.objects.all()
    context = {
        'juegos': juegos,
    }
    print("juegos:", juegos)  

    return render(request, 'juegos.html', context)

def carritoVer(request):
    productos_en_carrito = Juego.objects.all()
    carrito = Carrito(request)
    total= carrito.calcular_total()
    context = {
        'productos_en_carrito': productos_en_carrito,
        'total': total,
    }
    return render(request, 'carrito.html', context)

def agregar_juego(request, juego_id):
    carrito = Carrito(request)
    juego = Juego.objects.get(juego_id=juego_id)
    carrito.agregar(juego)
    return redirect("juegos")

def eliminar_juego(request, juego_id):
    carrito = Carrito(request)
    juego = Juego.objects.get(juego_id)
    carrito.eliminar(juego)
    return redirect("carrito.html")

def restar_juego(request, juego_id):
    carrito = Carrito(request)
    juego = Juego.objects.get(juego_id)
    carrito.restar(juego)
    return redirect("carrito.html")

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("juegos")

tiendajuegos/juegos/templates/carrito.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda de videojuegos</title>
    <link rel="stylesheet"  href="{% static 'css/stylecarrito.css' %}?v=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Tiendita</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'juegos' %}">Juegos</a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categorías
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Acción</a></li>
              <li><a class="dropdown-item" href="#">Aventura</a></li>
              <li><a class="dropdown-item" href="#">Deportes</a></li>
              <li><a class="dropdown-item" href="#">Estrategia</a></li>
              <li><a class="dropdown-item" href="#">Simulación</a></li>
              <li><a class="dropdown-item" href="#">RPG</a></li>
              <li><a class="dropdown-item" href="#">Terror</a></li>

              <li><hr class="dropdown-divider"></li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
            </li>
          </ul>

          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{%url 'login' %}">Iniciar sesión</a>
            </li>
          </ul>
          <form class="search-form" role="search">
            <input class="search-input" type="search" placeholder="Buscar" aria-label="Buscar">
            <button class="search-button" type="submit">Buscar</button>
        </form>            

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'carrito'%}">
                    <i class="bi bi-cart"></i>
                </a>
            </li>
        </ul>
        
      </div>
    </div>
  </nav>

<div class="alert alert-dark" role="alert">
  <div class="container">
    <div class='table-container'>
      <table class="table table-bordered table-dark">
        <thead>
          <tr>
            <th scope="row" colspan="3" class="text-center">CARRITO</th>
          </tr>
        <tr>
          <th scope="col">NOMBRE</th>
          <th scope="col">PRECIO</th>
          <th scope="col">CANTIDAD</th>
        </tr>
      </thead>
      <tbody>
        {% if request.session.carrito.items %}
        
        {% for key, value in request.session.carrito.items %}
          <tr>
            <td>{{value.nombre}}</td>
            <td>${{value.acumulado}}</td>
            <td>{{value.cantidad}}</td>
          </tr>
          
          
        {% endfor %}
      {% else %}
      <tr>
          <td colspan="3">
              <div class="alert alert-danger text-center"> Sin Productos </div>
          </td>
      </tr>
      {% endif %}
        <tr>
          <th scope="row">Total:</th>
          <td colspan="2">$ {{value.precio}}</td>
        </tr>
      </tbody>
      </table>
      <hr>
      </div>
    <div class="row text-center">
        <div class="col-6">
          <a href="{% url 'CLS' %}" class="btn btn-danger">Limpiar</a>
        </div>
        <div class="col-6">
          <a href="#" class="btn btn-success">Guardar</a>
        </div>
    </div>
  </div>
</div>
</body>

tiendajuegos/juegos/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda de videojuegos</title>
    <link rel="stylesheet"  href="{% static 'css/style.css' %}?v=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Tiendita</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'juegos' %}">Juegos</a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categorías
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Acción</a></li>
                  <li><a class="dropdown-item" href="#">Aventura</a></li>
                  <li><a class="dropdown-item" href="#">Deportes</a></li>
                  <li><a class="dropdown-item" href="#">Estrategia</a></li>
                  <li><a class="dropdown-item" href="#">Simulación</a></li>
                  <li><a class="dropdown-item" href="#">RPG</a></li>
                  <li><a class="dropdown-item" href="#">Terror</a></li>

                  <li><hr class="dropdown-divider"></li>
                </ul>
              </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
                </li>
              </ul>

              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'login' %}">Iniciar sesión</a>
                </li>
              </ul>
              <form class="search-form" role="search">
                <input class="search-input" type="search" placeholder="Buscar" aria-label="Buscar">
                <button class="search-button" type="submit">Buscar</button>
            </form>            

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'carrito'%}">
                        <i class="bi bi-cart"></i>
                    </a>
                </li>
            </ul>
            
          </div>
        </div>
      </nav>
    

    <main class="container py-4">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center">Bienvenido a Tiendita</h1>
            </div>
        </div>
            <div class="row">
                <div class="col-md-12">
                    <p>Encontrarás los mejores juegos a los mejores precios</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h2 class="text-center">Categorías</h2>
                </div>
            </div>

            {% for categoria in categorias %}
            <div class="row">
                <div class="col-md-4 mb-3">
                    <div class="card text-bg-dark">
                        <div id="carousel_{{ forloop.counter }}" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                {% for juego in categoria.juego_set.all %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    <img src="{{ juego.imagen.url }}" class="card-img-top d-block w-100" alt="{{ juego.nombre }}">
                                </div>
                                {% endfor %}
                            </div>
                            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_{{ forloop.counter }}" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carousel_{{ forloop.counter }}" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ categoria.nombre }}</h5>
                            <p class="card-text">{{ categoria.descripcion }}</p>
                            <button class="btn-ver">Ver juegos</button>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

    </main>

    <footer class="bg-dark text-light py-4">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <h5>Redes Sociales</h5>
              <ul class="list-unstyled">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Instagram</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <h5>Contacto</h5>
              <ul class="list-unstyled">
                <li>Teléfono: +123456789</li>
            </div>
          </div>
          <hr class="my-4">
          <p class="text-center">© 2024 Tiendita. Todos los derechos reservados.</p>
        </div>
      </footer>
      

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

tiendajuegos/juegos/templates/juegos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda de videojuegos</title>
    <link rel="stylesheet"  href="{% static 'css/style.css' %}?v=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Tiendita</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'juegos' %}">Juegos</a>
              </li>
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categorías
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Acción</a></li>
                  <li><a class="dropdown-item" href="#">Aventura</a></li>
                  <li><a class="dropdown-item" href="#">Deportes</a></li>
                  <li><a class="dropdown-item" href="#">Estrategia</a></li>
                  <li><a class="dropdown-item" href="#">Simulación</a></li>
                  <li><a class="dropdown-item" href="#">RPG</a></li>
                  <li><a class="dropdown-item" href="#">Terror</a></li>

                  <li><hr class="dropdown-divider"></li>
                </ul>
              </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'registro' %}">Registrarse</a>
                </li>
              </ul>

              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'login' %}">Iniciar sesión</a>
                </li>
              </ul>
              <form class="search-form" role="search">
                <input class="search-input" type="search" placeholder="Buscar" aria-label="Buscar">
                <button class="search-button" type="submit">Buscar</button>
            </form>            

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'carrito' %}">
                        <i class="bi bi-cart"></i>
                    </a>
                </li>
            </ul>
            
          </div>
        </div>
      </nav>
    

    <main class="container py-4">

  
      {% for juego in juegos %}
<div class="col-6">
    <div class="card" style="height: 10rem; width: 23rem; margin: 5px 0px; background-color: blueviolet;">

      <form method="POST" action="{% url 'agregar_juego' juego.juego_id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Agregar</button>
      </form>

        <div class="card-body">
            <h5 class="card-title">{{ juego.nombre }}</h5>
            <p class="card-text">{{ juego.categoria }}</p>
            <p class="card-text">{{ juego.precio }}</p>
        </div>
        
    </div>
</div>
{% endfor %}

    </main>

    <footer class="bg-dark text-light py-4">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <h5>Redes Sociales</h5>
              <ul class="list-unstyled">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Instagram</a></li>
              </ul>
            </div>
            <div class="col-md-4">
              <h5>Contacto</h5>
              <ul class="list-unstyled">
                <li>Teléfono: +123456789</li>
            </div>
          </div>
          <hr class="my-4">
          <p class="text-center">© 2024 Tiendita. Todos los derechos reservados.</p>
        </div>
      </footer>
      

      <script>
        function enviarFormulario(event, juegoId) {
            // Imprime el valor de juegoId en la consola del navegador
            console.log('Valor de juego.id:', juegoId);
            return true; // Devuelve true para enviar el formulario, false para cancelar el envío.
        }
      </script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

tiendajuegos/juegos/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar Sesión</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet"  href="{% static 'css/style.css' %}?v=1">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'inicio' %}">Tiendita</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>
              
            </ul>

              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'registro' %}">Registrarse</a>
                </li>
              </ul>
          </div>
        </div>
      </nav>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
               
                <div class="card text-bg-dark">
                    <div class="card-header">
                        Iniciar Sesion
                    </div>
                    <div class="card-body">
                        <form action="#" method="POST">
                            <div class="mb-3">
                                <label for="correo" class="form-label">Correo Electrónico</label>
                                <input type="email" class="form-control" id="correo" name="correo" required>
                            </div>
                            <div class="mb-3">
                                <label for="contrasena" class="form-label">Contraseña</label>
                                <input type="password" class="form-control" id="contrasena" name="contrasena" required>
                            </div>
                            <button type="submit" class="btn-ver">Iniciar Sesión</button>
                        </form>
                    </div>
                </div>
                <div class="mt-3 text-center">
                    <p>¿No tienes una cuenta? </p>
                    <a class="a-redireccion" href="{%url 'registro' %}">Regístrate aquí</a>
                </div>
            </div>
        </div>
    </div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

tiendajuegos/juegos/templates/registro.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Usuario</title>
    <link rel="stylesheet"  href="{% static 'css/style.css' %}?v=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary"  data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'inicio' %}">Tiendita</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>
              
            </ul>

              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{%url 'login' %}">Iniciar sesión</a>
                </li>
              </ul>
          </div>
        </div>
      </nav>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
               
                <div class="card text-bg-dark">
                    <div class="card-header">
                        Registro de Usuario
                    </div>
                    <div class="card-body">
                        <form action="#" method="POST">
                            <div class="mb-3">
                                <label for="nombre" class="form-label">Nombre</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" required>
                            </div>
                            <div class="mb-3">
                                <label for="correo" class="form-label">Correo Electrónico</label>
                                <input type="email" class="form-control" id="correo" name="correo" required>
                            </div>
                            <div class="mb-3">
                                <label for="contrasena" class="form-label">Contraseña</label>
                                <input type="password" class="form-control" id="contrasena" name="contrasena" required>
                            </div>
                            <button type="submit" class="btn-ver">Registrarse</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-3 text-center">
        <p>¿Ya tienes cuenta? </p>
        <a class= "a-redireccion"href="{%url 'login' %}">Inicia sesión aquí </a>
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>